const inputBox = document.getElementsByClassName('input-box')
const searchBtn = document.getElementsByid('searchBtn')
const weather_img = document.getElementsByClassName('weather-img')
const temprature = document.getElementsByClassName('temprature')
const discription = document.getElementsByClassName('discription')
const humidity = document.getElementsByid('humidity')
const wind_speed = document.getElementsByid('wind-speed')